services:
  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tienda_db
      POSTGRES_USER: tienda_user
      POSTGRES_PASSWORD: tienda_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tienda_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tienda_user -d tienda_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://tienda_user:tienda_password@database:5432/tienda_db
    depends_on:
      database:
        condition: service_healthy
    networks:
      - tienda_network

  webapp:
    build: ./webapp
    ports:
      - "8000:8000"
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
    networks:
      - tienda_network

  proxy:
    # Cambia el contexto de construcción para que apunte a la carpeta 'nginx'
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - webapp
    networks:
      - tienda_network

volumes:
  postgres_data:

networks:
  tienda_network:
    driver: bridge

